### ISSUE TITLE
Doesn't work with variables and calculations

### ISSUE THREAD

**Issue by felixsanz** [tricinel/postcss-color-hsla-fallback#1]
If input is:

```
hsl(
    var(--color-green-hue),
    calc(var(--color-green-sat) - 25%),
    calc(var(--color-green-lum) - 15%)
  );
```

the package doesn't do anything :(

**Comment by tricinel** [comment]
Thanks for the feedback @felixsanz! I'm not sure when I'll have time to take a look, will definitely try though! Happy to accept a pull request as well.

What would you expect it to do though? The plugin is meant to transform `hsl` to `hex` so if you're using color variables in there (and `calc` to boost), then that first needs to be preprocessed. Thoughts?
